### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by fortunee** [Victoradukwu/OOP#1]
### Nitpick

Good job implementing the [usejsdoc](usejsdoc.org) style guide. However, it's not a good practice to leave comments on every single line of code right beside it, because it makes it harder to read your code, it's better at the top. @Victoradukwu 
https://github.com/Victoradukwu/OOP/blob/bc8c2810cec35ec6cf94f46e406039b864362131/tests/test.js#L43

**Comment by Victoradukwu** [comment]
Thanks, Fortune for the review. I have taken note of it and strive to observe it subsequently.
